apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleappmvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleappmvc
  template:
    metadata:
      labels:
        app: sampleappmvc
    spec:
      containers:
       - name: sampleappmvc
         image: testingacr1608.azurecr.io/vtoansampleappnet
          ports:
          - containerPort: 80
